name: dynamic-workflows-dev
channels:
    - conda-forge
dependencies:
    # General dependencies
    - python=3.9
    - aiida-core>=2.0.0
    - graphviz
    # dev dependencies
    - pre-commit
    - ipykernel   # for running notebooks
    # used in example notebooks
    - loky
    - toolz
    - pandas
    - numpy
